# Generated by Django 5.0.3 on 2024-03-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
