# Generated by Django 5.0.3 on 2024-03-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('employees', '0004_alter_employee_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
